language: python

python:
  - "3.3"
  - "3.4"

install:
  - python setup.py install
  - pip install pyflakes
  - pip install pep8
  - pip install docutils
  - test $USE_SA == 1 && pip install sqlalchemy || true

before_script:
  - psql -c "create database aiopg;" -U postgres
  - psql -c "create user aiopg with password 'passwd';" -U postgres
  - psql -c "grant all privileges on database aiopg to aiopg;" -U postgres

script:
  - pep8 aiopg examples tests
  - pyflakes .
  - python runtests.py -v
  - python setup.py check -rms

addons:
  postgresql: "9.3"

env:
  global:
    - PYTHON=python
  matrix:
    - USE_SA=1
    - USE_SA=0

cache: apt
