language: python

python:
  - "3.3"

install:
  - python setup.py install
  - pip install pyflakes

before_script:
  - psql -c "create database aiopg;" -U postgres
  - psql -c "create user aiopg with password 'passwd';" -U postgres
  - psql -c "grant all privileges on database aiopg to aiopg;" -U postgres

script:
  - pyflakes .
  - python runtests.py -v

addons:
  postgresql: "9.3"
